----------------------------------------------------------------------------------------------------------
--

--Role-Based Access Control
      USE ROLE SECURITYADMIN;
      CREATE ROLE IF NOT EXISTS RL_EMPLOYEE;
      CREATE ROLE IF NOT EXISTS RL_MANAGER;
      CREATE ROLE IF NOT EXISTS RL_HR_REP;
      CREATE ROLE IF NOT EXISTS RL_FINANCE;
      CREATE ROLE IF NOT EXISTS RL_PRIVACY_ADMIN;


          --john can demo all 4 roles
          GRANT ROLE RL_EMPLOYEE TO USER JOHN;
          GRANT ROLE RL_MANAGER TO USER JOHN;
          GRANT ROLE RL_HR_REP TO USER JOHN;
          GRANT ROLE RL_FINANCE TO USER JOHN;
          GRANT ROLE RL_PRIVACY_ADMIN TO USER JOHN;
  

--Other dependencies
    use role sysadmin;
    CREATE WAREHOUSE IF NOT EXISTS ADHOC WITH WAREHOUSE_SIZE = XSMALL, INITIALLY_SUSPENDED = TRUE, auto_suspend = 180;
  
    CREATE OR REPLACE DATABASE PII_DEMO;
    CREATE OR REPLACE SCHEMA PII;
    CREATE OR REPLACE SCHEMA NONPII;

--Future-proof
USE ROLE ACCOUNTADMIN;
    GRANT SELECT ON FUTURE VIEWS IN SCHEMA NONPII TO PUBLIC;
    GRANT SELECT ON FUTURE TABLES IN SCHEMA PII TO RL_PRIVACY_ADMIN;
  
  
--grant permissions
    USE ROLE SYSADMIN;
    GRANT USAGE ON DATABASE PII_DEMO TO ROLE PUBLIC;
    GRANT USAGE ON SCHEMA NONPII TO ROLE PUBLIC;
    
    GRANT ALL ON SCHEMA PII TO ROLE RL_PRIVACY_ADMIN;
    GRANT ALL ON SCHEMA NONPII TO ROLE RL_PRIVACY_ADMIN;
    
    GRANT USAGE ON WAREHOUSE ADHOC TO ROLE PUBLIC;




-- CREATE A SAMPLE DATA TABLE
    USE ROLE SYSADMIN;

    CREATE OR REPLACE TABLE PII.EMPLOYEES(
    EMPLOYEE_ID VARCHAR,
    REPORTS_TO VARCHAR,
    SALARY NUMBER,
    DEPARTMENT VARCHAR,
    SSN VARCHAR
    );


    --INSERT DATA INTO PII.EMPLOYEES
    INSERT INTO PII.EMPLOYEES (EMPLOYEE_ID, REPORTS_TO, SALARY, DEPARTMENT, SSN) VALUES
        --MANAGER FOR ENGINEERING
        ('JOHN', 'SMITH', 200000, 'ENGINEERING','559-89-9170')
        --ENGINEERING TEAM MEMBERS
        ,('JUAN', 'JOHN', 135000, 'ENGINEERING','561-90-2911')
        ,('HELEN', 'JOHN', 160000, 'ENGINEERING','552-41-8376')
        ,('CARL', 'JOHN', 150000, 'ENGINEERING','541-94-3370')
        --MANAGER FOR MARKETING
        ,('LINDA', 'ESTRADA', 220000, 'MARKETING','530-55-4196')
        --MARKETING TEAM
        ,('JACOB', 'LINDA', 150000, 'MARKETING','645-93-4603')
        ,('LINDA', 'LINDA', 220000, 'MARKETING','593-88-3817')
        ,('LORI', 'LINDA', 180000, 'MARKETING','641-36-7829')
        --HR MANAGER
        ,('JANE', 'BECK', 175000, 'HR','632-95-4531')
        --HR TEAM
        ,('MARK', 'JANE', 130000, 'HR','557-75-6294')
        ,('LINDA', 'JANE', 120000, 'HR','539-90-4851')
        ,('BRANDON', 'JANE', 140000, 'HR','595-93-1035');

  
  
 --Smoke test
 select Department, Employee_Id, Reports_to, Salary, SSN
 from PII.EMPLOYEES order by 1,2,3;
 
