----------- CLEANUP QUICK TO RERUN DEMO ------------

USE ROLE RL_PRIVACY_ADMIN;
use database pii_demo;
DROP VIEW if exists NONPII.V_MASK_EMP_INFO;
DROP VIEW if exists NONPII.V_MASK_EMP_INFO_RLS;

USE ROLE ACCOUNTADMIN;
ALTER TABLE PII.EMPLOYEES MODIFY COLUMN SALARY UNSET MASKING POLICY;
ALTER TABLE PII.EMPLOYEES MODIFY COLUMN SSN UNSET MASKING POLICY;
DROP MASKING POLICY if exists PII.SALARY_MASK;
DROP MASKING POLICY if exists PII.SSN_MASK;
 


/*
  
------------- CLEANUP FULL ---------------
USE ROLE RL_PRIVACY_ADMIN;
use database pii_demo;
DROP VIEW if exists NONPII.V_MASK_EMP_INFO;
DROP VIEW if exists NONPII.V_MASK_EMP_INFO_RLS;

  
USE ROLE ACCOUNTADMIN;
ALTER TABLE PII.EMPLOYEES MODIFY COLUMN SALARY UNSET MASKING POLICY;
ALTER TABLE PII.EMPLOYEES MODIFY COLUMN SSN UNSET MASKING POLICY;
DROP MASKING POLICY PII.SALARY_MASK;
DROP MASKING POLICY PII.SSN_MASK;
 
USE ROLE ACCOUNTADMIN;
DROP DATABASE if exists PII_DEMO;
  
USE ROLE SYSADMIN;
DROP WAREHOUSE if exists ADHOC;
  
USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS RL_EMPLOYEE;
DROP ROLE IF EXISTS RL_MANAGER;
DROP ROLE IF EXISTS RL_HR_REP;
DROP ROLE IF EXISTS RL_PRIVACY_ADMIN;




*/
